version: "3.9"
networks: 
  testlink:
    name: testlink
services:
  testlink-mysql:
    image: mysql:latest
    networks:
    - testlink
    restart: unless-stopped
    user: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
    - mysql:/var/lib/mysql

  testlink-app:
    image: testlink:1.9.20
    restart: unless-stopped
    depends_on:
      testlink-mysql:
        condition: service_started
    networks:
    - testlink
    ports:
    - 8080:80
    volumes:
    - ./:/var/www/testlink
    - ./logs:/var/testlink/logs
    - ./upload_area:/var/testlink/upload_area

volumes:
  mysql:
